const ROOT = require('path').join(__dirname, '..', '..');
let s = require(ROOT + '/tools/load-page.js')();
const mkEl = () => ({ style: {}, classList: { add() {}, remove() {}, toggle() {} }, append() {}, addEventListener() {}, querySelectorAll() { return []; }, setPointerCapture() {}, getContext() { return ctx; }, innerHTML: '' });
const ctx = new Proxy({}, { get: (t, k) => k === 'createRadialGradient' || k === 'createLinearGradient' ? () => ({ addColorStop() {} }) : k in t ? t[k] : () => {}, set: (t, k, v) => { t[k] = v; return true; } });
globalThis.document = { getElementById: () => mkEl(), createElement: () => mkEl(), activeElement: null };
globalThis.innerWidth = 1200; globalThis.innerHeight = 800; globalThis.devicePixelRatio = 1; globalThis.addEventListener = () => {};
globalThis.requestAnimationFrame = () => {}; globalThis.Path2D = class { moveTo() {} lineTo() {} arc() {} closePath() {} rect() {} addPath() {} }; globalThis.performance = { now: () => 0 };
s = s.replace(/requestAnimationFrame\(loop\);\s*$/, '') + `globalThis.T = { focusOn, draw, computePositions, set logR(v) { logR = v; }, get focus() { return focus; }, labelHits, hits, pickAt, activate, SUN, PLANETS, MOONS, PROBES, COMETS, METEORITES, selectMeteo, get selMeteo() { return selMeteo; }, EARTHB, LAYERS };`;
new Function(s)();
const T = globalThis.T;
T.computePositions(Date.now() / 864e5 - 10957.5);
let ok = 0, fail = 0;
const tryAll = (what) => { for (const l of T.labelHits) { const x = (l.x0 + l.x1) / 2, y = (l.y0 + l.y1) / 2; T.focusOn(T.SUN, 'overview'); const before = T.focus; T.activate(T.pickAt(x, y)); const good = (l.ref.type && l.ref.lat !== undefined) ? T.selMeteo === l.ref : T.focus === l.ref; good ? ok++ : fail++; if (!good) console.log('ECHEC', what, l.ref.name, '-> clic donne', (T.pickAt(x, y) || {}).name); } };
T.logR = Math.log(8e9); T.draw(1); console.log('vue d\'ensemble : étiquettes', T.labelHits.length); tryAll('ens');
T.focusOn(T.PLANETS[4], 'system'); T.logR = Math.log(3e6); T.draw(1); console.log('Jupiter+lunes : étiquettes', T.labelHits.length); tryAll('jup');
T.logR = Math.log(3e10); T.focusOn(T.SUN, 'overview'); T.logR = Math.log(3e10); T.draw(1); console.log('3e10 : étiquettes', T.labelHits.length); tryAll('3e10');
T.selectMeteo(T.METEORITES[0]); T.logR = Math.log(2e4); T.draw(1); console.log('Terre+pins : étiquettes', T.labelHits.length); tryAll('terre');
T.LAYERS.labels = false; T.draw(1); console.log('étiquettes masquées -> zones cliquables :', T.labelHits.length);
console.log('clics sur texte OK', ok, 'échecs', fail);
