const ROOT = require('path').join(__dirname, '..', '..');
let s = require(ROOT + '/tools/load-page.js')();
const mkEl = () => ({ style: {}, classList: { add() {}, remove() {}, toggle() {} }, append() {}, addEventListener() {}, querySelectorAll() { return []; }, setPointerCapture() {}, getContext() { return ctx; }, innerHTML: '' });
const ctx = new Proxy({}, { get: (t, k) => k === 'createRadialGradient' || k === 'createLinearGradient' ? () => ({ addColorStop() {} }) : k in t ? t[k] : () => {}, set: (t, k, v) => { t[k] = v; return true; } });
globalThis.document = { getElementById: () => mkEl(), createElement: () => mkEl(), activeElement: null };
globalThis.innerWidth = 1200; globalThis.innerHeight = 800; globalThis.devicePixelRatio = 1; globalThis.addEventListener = () => {};
globalThis.requestAnimationFrame = () => {}; globalThis.Path2D = class { moveTo() {} lineTo() {} arc() {} closePath() {} rect() {} addPath() {} }; globalThis.performance = { now: () => 0 };
s = s.replace(/requestAnimationFrame\(loop\);\s*$/, '') + `globalThis.T = { LAYERS, LAYER_DEFS, focusOn, draw, computePositions, COMETS, PROBES, MOONS, PLANETS, SUN, set logR(v) { logR = v; }, get hits() { return hits; }, buildLayers, selectMeteo, METEORITES };`;
new Function(s)();
const T = globalThis.T;
T.computePositions(Date.now() / 864e5 - 10957.5);
const count = (R, f) => { T.logR = Math.log(R); T.draw(1); return T.hits.filter(f).length; };
console.log('tout actif @ 3e10 : comètes', count(3e10, h => h.b.comet), 'sondes', count(3e10, h => h.b.probe));
T.LAYERS.comets = false; T.LAYERS.probes = false; console.log('comets+probes off :', count(3e10, h => h.b.comet), count(3e10, h => h.b.probe));
T.LAYERS.comets = true; T.LAYERS.probes = true;
T.focusOn(T.PLANETS[4], 'system'); T.LAYERS.moons = false; T.logR = Math.log(3e6); T.draw(1); console.log('lunes off : hits lunes', T.hits.filter(h => h.b.parent && h.b.parent !== T.SUN).length);
T.focusOn(T.MOONS[3]); console.log('focus lune réactive le calque :', T.LAYERS.moons);
T.LAYERS.pins = false; T.selectMeteo(T.METEORITES[0]); console.log('météorite réactive pins :', T.LAYERS.pins);
for (const d of T.LAYER_DEFS) { T.LAYERS[d[1]] = false; } T.draw(1); T.buildLayers(); for (const d of T.LAYER_DEFS) T.LAYERS[d[1]] = true; T.draw(1);
console.log('tous calques off puis on : dessin OK');
