// Récit d'Apollo 11 (affiché pendant l'aperçu et le vol, panneau à gauche) ; chargé après story.js. Photos : data/story/apollo11-*.jpg (Wikimedia Commons, NASA, domaine public, licences vérifiées via l'API).
// Les chiffres historiques viennent de la mémoire de l'auteur : à vérifier avant publication. Les notes sont liées aux événements de la mission (clé = événement de la simulation).
STORIES.apollo11 = {
  title: 'Apollo 11 — les premiers pas sur la Lune', subtitle: '16-24 juillet 1969 · États-Unis (NASA)',
  facts: [
    ['Équipage', 'Neil Armstrong (commandant), Edwin « Buzz » Aldrin (pilote du LEM), Michael Collins (pilote du module de commande)'],
    ['Décollage', '16 juillet 1969, 13 h 32 min UTC, pas de tir 39A, Centre spatial Kennedy (Floride)'],
    ['Fusée', 'Saturn V (SA-506) : 110 m, ≈ 2 900 t, 3 étages (S-IC, S-II, S-IVB)'],
    ['Vaisseau', 'module de commande et de service « Columbia » + module lunaire « Eagle » (LEM, ≈ 15 t)'],
    ['Orbite d’attente', '185 km, 1 tour et demi, puis injection translunaire à T+2 h 44 (≈ 3,14 km/s ajoutés)'],
    ['Alunissage', '20 juillet 1969, 20 h 17 min UTC, Mer de la Tranquillité (0,67° N, 23,47° E)'],
    ['Premier pas', '21 juillet, 02 h 56 UTC : « Un petit pas pour l’homme, un bond de géant pour l’humanité »'],
    ['Sur la Lune', '21 h 36 min sur place, 2 h 31 min de sortie, 21,5 kg de roches rapportées'],
    ['Retour', 'décollage lunaire 21 juillet 17 h 54 UTC, amerrissage dans le Pacifique le 24 juillet à 16 h 50 UTC (≈ 195 h de mission)'],
  ],
  sections: [
    { h: 'Pourquoi la Lune ?', p: 'En 1961, le président Kennedy fixe l’objectif d’envoyer un homme sur la Lune et de le ramener sur Terre avant la fin de la décennie, en pleine course à l’espace avec l’URSS. Apollo 11 est la première mission à poser des hommes sur un autre astre.' },
    { h: 'Le décollage', p: 'Le S-IC brûle 168 s (cinq moteurs F-1, 34 MN de poussée) et emmène la fusée à ≈ 70 km et 2,4 km/s ; le S-II prend le relais, puis le S-IVB met le vaisseau en orbite d’attente à 185 km. La simulation rejoue cette montée avec le moteur physique du projet (traînée, rotation de la Terre, gravité, étages) : la Saturn V part vers l’est-nord-est (azimut ≈ 72°).' },
    { h: 'L’injection translunaire (TLI)', p: 'Après un tour et demi de vérification, le S-IVB se rallume 347 s (≈ 3,14 km/s) : le vaisseau quitte l’orbite terrestre pour une ellipse qui croise l’orbite de la Lune. Ici le Δv et la phase de la Lune sont trouvés par recherche numérique (problème des trois corps Terre-Lune-vaisseau) pour passer à 110 km de la Lune.' },
    { h: 'Le vol vers la Lune', p: 'Environ trois jours : la vitesse chute de 10,8 km/s à moins de 1 km/s quand le vaisseau monte, puis la gravité lunaire le reprend. Le CSM se sépare du S-IVB, fait demi-tour, s’amarre au LEM caché dans l’étage et l’extrait. Dans la simulation le transfert dure ≈ 86 h (75,8 h en vrai) : la Lune est sur une orbite circulaire dans le plan de la montée, plus simple que la vraie.' },
    { h: 'L’orbite lunaire', p: 'Au passage à 110 km, le moteur du CSM freine (≈ 800 m/s) : mise en orbite elliptique, puis circulaire à 110 km. Armstrong et Aldrin passent dans le LEM, qui se sépare de Columbia (Collins reste seul en orbite).' },
    { h: 'La descente d’Eagle', p: 'Une petite poussée abaisse le point le plus bas de l’orbite à 15 km ; au périgée, 12 min de descente motorisée freinent le LEM de ≈ 1,7 km/s à zéro. Ici la trajectoire est un polynôme de degré 5 (position, vitesse, accélération aux deux bouts), poussée limitée à 45 kN comme le vrai moteur. En vrai, Armstrong a repris les commandes pour éviter un champ de rochers : il restait environ 25 s de carburant.' },
    { h: 'Sur la Lune', p: 'Eagle se pose dans la Mer de la Tranquillité. Armstrong descend l’échelle environ 6 h 40 après l’alunissage, Aldrin le rejoint 19 min plus tard : drapeau, expériences, 21,5 kg d’échantillons. L’étage de descente reste sur place avec la plaque « Nous sommes venus en paix au nom de toute l’humanité ».' },
    { h: 'Remontée, rendez-vous, retour', p: 'L’étage de remontée (4,7 t, un seul moteur sans redondance) décolle, rejoint Columbia en orbite, les astronautes repassent dans le module de commande et l’étage est largué. Le moteur du CSM donne alors ≈ 1,1 km/s : l’injection transterrestre. Plus de trois jours plus tard le module de service est largué et le module de commande rentre dans l’atmosphère à ≈ 11 km/s (pic de ≈ 6,7 g), puis trois grands parachutes le ramènent à ≈ 9 m/s.' },
    { h: 'Ce que la simulation simplifie', p: 'Tout dans le plan de la montée (pas d’inclinaison de l’orbite lunaire ni de correction à mi-parcours), Lune sur orbite circulaire, alunissage au point de l’équateur du plan, rendez-vous final « fondu » (pas de CSI/CDH/TPI), rentrée sans portance, amerrissage en un point qui n’est pas celui de 1969. Masses, poussées et durées écrites de mémoire : à vérifier.' },
  ],
  photos: [
    { src: 'data/story/apollo11-launch.jpg', cap: 'Décollage de la Saturn V d’Apollo 11, 16 juillet 1969', credit: 'NASA — domaine public' },
    { src: 'data/story/apollo11-crew.jpg', cap: 'L’équipage : Armstrong, Collins et Aldrin', credit: 'NASA — domaine public' },
    { src: 'data/story/apollo11-eagle.jpg', cap: 'Le LEM Eagle en orbite lunaire, vu depuis Columbia', credit: 'NASA — domaine public' },
    { src: 'data/story/apollo11-aldrin.jpg', cap: 'Buzz Aldrin sur la Lune, photographié par Neil Armstrong', credit: 'Neil Armstrong / NASA — domaine public' },
    { src: 'data/story/apollo11-bootprint.jpg', cap: 'L’empreinte de la botte d’Aldrin dans le sol lunaire', credit: 'Buzz Aldrin / NASA — domaine public' },
    { src: 'data/story/apollo11-splash.jpg', cap: 'Amerrissage de Columbia dans le Pacifique, 24 juillet 1969', credit: 'NASA — domaine public' },
  ],
  notes: [
    { t: 0, text: 'T+0 — 16 juillet 1969, 13 h 32 UTC. Les cinq moteurs F-1 du S-IC s’allument : la Saturn V quitte la rampe 39A en Floride avec Armstrong, Aldrin et Collins.' },
    { key: 'fairing', text: 'T+3 min 17 s — largage de la tour de sauvetage, devenue inutile.' },
    { key: 'epcsep', text: 'Séparation du S-IC : le deuxième étage continue vers l’orbite.' },
    { key: 'sat', text: 'Orbite d’attente de 185 km atteinte, avec la Terre qui tourne dessous. Les astronautes vérifient le vaisseau pendant un tour et demi.' },
    { key: 'tli', text: 'T+2 h 44 — le S-IVB se rallume 347 s : injection translunaire (≈ 3,14 km/s). Le vaisseau quitte l’orbite terrestre.' },
    { key: 'sivbsep', text: 'Manœuvre de transposition : Columbia se sépare du S-IVB, fait demi-tour, s’amarre au LEM et l’extrait de l’étage.' },
    { key: 'loi1', text: 'Après trois jours de vol, freinage de 6 min derrière la Lune : Apollo 11 est capturé par la gravité lunaire (110 km d’altitude au plus près).' },
    { key: 'loi2', text: 'Deuxième freinage : l’orbite devient circulaire à ≈ 110 km. Un tour de Lune dure ≈ 2 h.' },
    { key: 'undock', text: 'Armstrong et Aldrin sont dans Eagle : séparation. Collins reste seul à bord de Columbia.' },
    { key: 'doi', text: 'Petite poussée de descente : le point bas de l’orbite d’Eagle passe à 15 km au-dessus de la surface.' },
    { key: 'pdi', text: 'Début de la descente motorisée : le moteur d’Eagle freine ≈ 1,7 km/s pendant ≈ 12 min.' },
    { key: 'land', text: 'Alunissage dans la Mer de la Tranquillité. « Houston, ici la base de la Tranquillité. L’Aigle s’est posé. »' },
    { key: 'step', text: 'Neil Armstrong descend l’échelle et pose le pied gauche sur le sol lunaire : « Un petit pas pour l’homme, un bond de géant pour l’humanité. »' },
    { key: 'eva', text: 'Fin de la sortie : drapeau planté, expériences installées, 21,5 kg de roches. Retour dans Eagle.' },
    { key: 'lift', text: 'Décollage de l’étage de remontée (moteur unique, pas de redondance). L’étage de descente reste sur la Lune.' },
    { key: 'ins', text: 'Eagle est en orbite lunaire basse (≈ 17 × 85 km), derrière Columbia.' },
    { key: 'rdv', text: 'Approche finale vers Columbia (dans la simulation, un fondu scripté).' },
    { key: 'dock', text: 'Amarrage d’Eagle à Columbia. Les astronautes repassent dans le module de commande avec les échantillons.' },
    { key: 'lmjett', text: 'L’étage de remontée est largué : il reste en orbite lunaire.' },
    { key: 'tei', text: 'Injection transterrestre : le moteur du module de service pousse ≈ 1,1 km/s pour quitter la Lune et revenir vers la Terre.' },
    { key: 'smsep', text: 'Le module de service, qui a fait tout le travail, est largué : seul le module de commande va rentrer.' },
    { key: 'ei', text: 'Entrée dans l’atmosphère à ≈ 11 km/s, bouclier thermique en avant : le plasma enveloppe le module.' },
    { key: 'gmax', text: 'Pic de décélération (≈ 6,7 g dans la simulation).' },
    { key: 'drogue', text: 'Parachutes stabilisateurs à ≈ 7 km d’altitude.' },
    { key: 'main', text: 'Trois grands parachutes : le module se pose sur l’eau à ≈ 9 m/s.' },
    { key: 'splash', text: 'Amerrissage dans l’océan Pacifique. Les astronautes sont récupérés par l’USS Hornet, puis placés en quarantaine 21 jours.' },
  ],
};
